### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/hello-world#2]
Port the activity to Python 3 and the Sugar Toolkit for GTK+ 3.

Requires some of https://github.com/sugarlabs/sugar-toolkit-gtk3/issues/382 to be completed.

**Comment by Aniket21mathur** [comment]
@quozl any need to keep this issue open?

**Comment by quozl** [comment]
Thanks for asking.  Happy to explain.  Best reason is that https://github.com/sugarlabs/hello-world/pull/3 is not yet merged.

Why is it not yet merged?  There's more to our ecosystem than GitHub.  While we have released v0.113 of the toolkit, with Python 3 support, it has not been packaged by Ubuntu or Fedora yet, so there's no rush to merge Python 3 ports of activities since there is no place that they can be used, and if they _are_ released accidentally the systems running v0.112 of the toolkit will fail to run them.  This quandry is possibly called a "[flag day change](https://en.wikipedia.org/wiki/Flag_day_(computing))".  I'm trying to control for that, see https://github.com/sugarlabs/sugar-docs/commit/af47a5ab069158b2b087ad419b72c9d67a76bcae for a recent example.

On the other hand, Hello World is not a core activity; it actually does nothing but serve as an example.

This isn't really the right place to discuss this, because so few people are watching this repository, but here's my current plan; either;
* keep the pull requests open until both Fedora and Ubuntu have packaged v0.113 for Python 2 and Python 3,
* merge the pull requests into a _python3_ branch, or;
* create a _python2_ branch for ongoing maintenance and merge the pull requests into _master_ branch.

A better place to discuss would be the sugar-devel@ mailing list.

**Comment by Aniket21mathur** [comment]
@quozl . I agree with you, we can merge into master after v0.113 gets packaged by Ubuntu or Fedora. It would be better to merge it into python3 branch now. Just going through the work done till now in the port to python 3 project for GSoC '19 proposal. Thanks for answering :sweat_smile:  .

**Comment by quozl** [comment]
It is in _python3_ branch now, thanks.
